### ISSUE TITLE
Scaling is in correct with the new larger art boards in latest update

### ISSUE THREAD

**Issue by JGonzo10** [adamdehaven/Specify#18]
Illustrator just came out with a minor update.  Minor update includes being able go much larger with the art boards.  We created an artboard that is 1000in x 1000in.  We draw a 500" x 500" square.  At 1/1 it provides a measurement of 50.00 in x 50.00 in
![Screen Shot 2020-06-17 at 11 04 24 AM](https://user-images.githubusercontent.com/42037576/84921984-d4c6df80-b08a-11ea-9cba-b587777297ec.png)

**Comment by adamdehaven** [comment]
Your new document is created on a large canvas if one of the following settings is applied in the New Document dialog:
- Artboard size larger than 227 inches (default canvas size) specified in Feet, Meters, Yards, or Feet and Inches.
- High number of artboards that cannot be accommodated in the default canvas size.

The unit issue appears to be a known issue:

> New units that are introduced for the large-sized canvas (feet, feet-inch, meter, yard) have representation issue for decimal numbers.

I can adjust the label output based on a multiplier, which is what I'm testing now. @JGonzo10 I would love if you want to help test, once I get this potential fix in place.

[Source](https://helpx.adobe.com/illustrator/kb/large-sized-canvas-troubleshooting.html)

**Comment by JGonzo10** [comment]
Adam:

I would like to help and test it out for you.  I work at a sign shop, so we work with a lot of larger graphics.  This new increased artboard is
wonderful for people in our industry.  Please let me know when you have aversion ready for me to test.

**Comment by adamdehaven** [comment]
Looking through adobe's documentation, it doesn't appear that there is a way to "detect"  when a large canvas is being used other than simply by measuring the artboard. 

The problem is, once the artboard exceeds 227 inches in either width or height, the values returned to the script appear to be 1/10 of their original value. 

For example, if I create an artboard that is 400 inches wide by 300 inches tall (so Illustrator uses a "large canvas"), when I check the size of the artboard using `app.activeDocument.width` it returns 40 instead of 400.

@JGonzo10 since I can't seem to currently detect when a large canvas is being used, would another checkbox in the options suffice for now? When checked, it would multiply the measurement by 10, therefore giving the proper value.

**Comment by adamdehaven** [comment]
I have since found the `app.document.scaleFactor` that gives me exactly what I needed. I have updated the script with the fix to [version 2.0.2](https://github.com/adamdehaven/Specify/releases/tag/v2.0.2).

In addition, the [free Adobe Exchange extension](https://exchange.adobe.com/creativecloud.details.104123.specify.html) has since been approved 🎉 

The current version of the extension is 2.0.0, meaning it doesn't yet have the fix; however, the 2.0.1 version should be approved in the next 24 hours. 

@JGonzo10 if you're an Illustrator CC user, I'd recommend going ahead and downloading the extension and it should trigger an update via the Creative Cloud app in the next 24 hours. Let me know if you have any issues, and thanks for submitting this bug!

**Comment by JGonzo10** [comment]
This is great news.  Thank you for looking into this.  I will give this a
shot and download through Adobe Exchange.  I will continue to use this
myself along with my team and let you know of any issues.

Joel Gonzales

**Comment by adamdehaven** [comment]
@JGonzo10 I needed to make an update to the scale factor. You'll want to download the latest version [2.0.2](https://github.com/adamdehaven/Specify/releases/tag/v2.0.2)

**Comment by JGonzo10** [comment]
Thank you for the heads up.  I also installed it using Exchange.  That
should update on its own within the next few days, correct?

**Comment by adamdehaven** [comment]
@JGonzo10 Yes, the Exchange extension should auto-update (assuming you have the Creative Cloud app running), although it's still currently pending approval. Hopefully it will be approved in the next 24 hours.

**Comment by JGonzo10** [comment]
Adam:

Just following up on the approval of the updates on exchange. Is it still
pending?

Thanks,

Joel Gonzales
JGonzo10@gmai\

**Comment by adamdehaven** [comment]
@JGonzo10 I believe they only do approvals Monday-Friday, so hopefully it will be approved today or tomorrow.

**Comment by adamdehaven** [comment]
@JGonzo10 [the new version of the extension is available now](https://exchange.adobe.com/creativecloud.details.104123.specify.html)

**Comment by JGonzo10** [comment]
Will you be updating the Adobe extension to be compatible with the new 2021
version of Illustrator?

What is interesting is the extension isn't compatible, but it says it is on
the website, but if you install the script, it seems to be working fine.

Thanks,

Joel Gonzales
708-289-2305
JGonzo10@gmail.com

**Comment by adamdehaven** [comment]
@JGonzo10 I’m kinda new at Adobe Extensions, so I’m guessing I’ll just need to update the supported versions in Adobe Exchange. I’ll look into this in the coming days and push an update — thanks for the head’s up! 🙌

**Comment by adamdehaven** [comment]
@JGonzo10 can you go into Illustrator Menu > Help > About Illustrator and let me know what version you show?

**Comment by JGonzo10** [comment]
It shows version 25.0

Joel Gonzales
708-289-2305
JGonzo10@gmail.com

**Comment by adamdehaven** [comment]
@JGonzo10 I just pushed an update here to the extension. I installed on my Windows computer and it runs with no issue.

You can run manually by downloading the newest version (3.0.0), or, hopefully Adobe will approve the new version in Exchange over the next couple days, then you can update through Creative Cloud. 

I wouldn't mind seeing what is happening on your end (you've been so helpful in the past). If you wouldn't mind helping me take a look, email me at `adam@dehaven.org` and maybe we can get together online later this week and take a closer look? I'd like to be able to solve this issue for everyone and prevent it from happening in the future.

**Comment by JGonzo10** [comment]
Great! I just emailed you more info on your personal email address.

Joel Gonzales
708-289-2305
JGonzo10@gmail.com
