### ISSUE TITLE
Just purchased the plugin, Scecify.jsx but it will not install

### ISSUE THREAD

**Issue by danielsevier** [adamdehaven/Specify#22]
Just purchased the plugin, Scecify.jsx but it will not install and does not appear under my Adobe Marketplace.

**Comment by adamdehaven** [comment]
Hey @danielsevier, I'm sorry you're having trouble with the extension. You're actually the second person to report this to me today. I haven't changed the extension since last month, so I'm leaning towards the issue being on Adobe's side.

The first thing I'd recommend is making sure both the Adobe Creative Cloud desktop app and Illustrator are both up to date. Then, try uninstalling the extension, and then trying to reinstall it.

I can tell you that currently (unless things changed recently), Creative Cloud extensions are not compatible with M1 Apple computers, so if the Mac you're running is on an M1 chip, I believe that could be the issue.

I can't offer too much more info on the troubleshooting side since all users' computers are different.

If these steps do not resolve the issue for you, I would recommend emailing asupport@adobe.com as again, my ability to troubleshoot are limited.

You can also refer to this Adobe link:
https://helpx.adobe.com/uk/creative-cloud/kb/troubleshoot-common-addon-installation-issues.html#still-facing-issues

I'll leave this issue open for you to respond to. I'm sorry I can't be more help at the moment -- I know there isn't an issue with the extension itself.

**Comment by adamdehaven** [comment]
Connected with the user on Twitter, so closing the issue here.
