### ISSUE TITLE
Feedback/Request

### ISSUE THREAD

**Issue by KevinConsen** [adamdehaven/Specify#6]
Thank you SO MUCH!!!

I've been searching for this for weeks, this is EXACTLY what I wanted to specify design dimensions.

Few points of feedback/requests if you don't mind:

Is there a way for the script to remember previous settings? Especially the decimal setting. Would save me a whole bunch of clicks.

Is there a way to key bind the script to run (f.e. using arrow keys for selecting the dimension.

Any chance you could make a similar script, or adjust this one, to allow defining colors in a similar way?  Something resulting in:

![screen shot 2016-11-11 at 09 59 22](https://cloud.githubusercontent.com/assets/6752605/20209767/65054e20-a7f6-11e6-8a2e-9a150e014759.png)

That would be amazing and my gratitude would be eternal!

I'm sorry if this isn't the appropriate place for these comments, I couldn't find a better place.

**Comment by adamdehaven** [comment]
First of all, thanks for the feedback!

Regarding your feature requests:
1. The script is essentially JavaScript so there's no way to remember settings (at least no way I can think of off-hand. I'll look into it though). In the meantime, you could open the `.jsx` file and change the default number of decimals.
   - **UPDATE**: After doing a little research, it seems possible to store settings in a file and then update them whenever the script is ran. This would load the last-used settings instead of the default. Still doing research.
2. I assume you mean key bind the options in the dialog window that pops up?
3. Defining colors is an interesting idea, and actually something I would use a TON. I'll look into it, but can't promise anything soon.

(This is the perfect place for comments/feature requests, so keep them coming!)

**Comment by adamdehaven** [comment]
@KevinConsen I have a new build of the script that allows for persistent options (until you close the application) that I think covers your first feature suggestion. Would you want to download the build and test it out for me? Let me know and I'll give you access to download

**Comment by KevinConsen** [comment]
Absolutely, anything I can do to help!

**Comment by adamdehaven** [comment]
@KevinConsen I have pushed version 1.2 which enables persistent settings. If you could test, and let me know if you see any issues, I'd appreciate it (comment on Issue #7)

**Comment by KevinConsen** [comment]
@adamdehaven will do!! Any ETA on the color specification? That would make this a perfect design companion haha! (A)

**Comment by KevinConsen** [comment]
@adamdehaven seems to work just fine!

**Comment by adamdehaven** [comment]
@KevinConsen I haven't had a chance to look into the color specification as of yet. If I'm able to come up with something, it will be super-useful for me at my job as well. Watch Issue #8 for future updates, and thanks for your input!
